import {
  Circle,
  Square,
  Star,
  Heart,
  Zap,
  Target,
  Flag,
  Bookmark,
  Bell,
  Check,
  X,
  AlertTriangle,
  Info,
  HelpCircle,
  Lightbulb,
  Rocket,
  Trophy,
  Gift,
  Coffee,
  Music,
  Camera,
  Mail,
  Phone,
  Globe,
  Home,
  User,
  Users,
  Settings,
  Lock,
  Unlock,
  Eye,
  EyeOff,
  Edit,
  Trash,
  Plus,
  Minus,
  Search,
  Filter,
  Download,
  Upload,
  Share,
  Link,
  Unlink,
  Clipboard,
  FileText,
  Folder,
  Database,
  Cloud,
  Server,
  Cpu,
  Wifi,
  Battery,
  Power,
  Play,
  Pause,
  StopCircle,
  RefreshCw,
  RotateCw,
  ArrowUp,
  ArrowDown,
  ArrowLeft,
  ArrowRight,
  ChevronUp,
  ChevronDown,
  ChevronLeft,
  ChevronRight,
  type LucideIcon,
} from 'lucide-react';

export const GENERIC_NODE_ICONS: Record<string, LucideIcon> = {
  circle: Circle,
  square: Square,
  star: Star,
  heart: Heart,
  zap: Zap,
  target: Target,
  flag: Flag,
  bookmark: Bookmark,
  bell: Bell,
  check: Check,
  x: X,
  warning: AlertTriangle,
  info: Info,
  help: HelpCircle,
  lightbulb: Lightbulb,
  rocket: Rocket,
  trophy: Trophy,
  gift: Gift,
  coffee: Coffee,
  music: Music,
  camera: Camera,
  mail: Mail,
  phone: Phone,
  globe: Globe,
  home: Home,
  user: User,
  users: Users,
  settings: Settings,
  lock: Lock,
  unlock: Unlock,
  eye: Eye,
  eyeOff: EyeOff,
  edit: Edit,
  trash: Trash,
  plus: Plus,
  minus: Minus,
  search: Search,
  filter: Filter,
  download: Download,
  upload: Upload,
  share: Share,
  link: Link,
  unlink: Unlink,
  clipboard: Clipboard,
  file: FileText,
  folder: Folder,
  database: Database,
  cloud: Cloud,
  server: Server,
  cpu: Cpu,
  wifi: Wifi,
  battery: Battery,
  power: Power,
  play: Play,
  pause: Pause,
  stop: StopCircle,
  refresh: RefreshCw,
  rotate: RotateCw,
  arrowUp: ArrowUp,
  arrowDown: ArrowDown,
  arrowLeft: ArrowLeft,
  arrowRight: ArrowRight,
  chevronUp: ChevronUp,
  chevronDown: ChevronDown,
  chevronLeft: ChevronLeft,
  chevronRight: ChevronRight,
};
