import { Node, Edge } from '@xyflow/react';

export interface DiagramTemplate {
    id: string;
    name: string;
    description: string;
    category: 'ai-agents' | 'architecture' | 'flowchart' | 'general';
    thumbnail?: string;
    nodes: Node[];
    edges: Edge[];
}

export const DIAGRAM_TEMPLATES: DiagramTemplate[] = [
    {
        id: 'single-agent',
        name: 'Single AI Agent',
        description: 'Basic AI agent with tools and memory',
        category: 'ai-agents',
        nodes: [
            {
                id: 'user-1',
                type: 'user',
                position: { x: 50, y: 150 },
                data: { label: 'User' },
            },
            {
                id: 'input-1',
                type: 'input',
                position: { x: 200, y: 150 },
                data: { label: 'Input' },
            },
            {
                id: 'agent-1',
                type: 'agent',
                position: { x: 400, y: 100 },
                data: { label: 'AI Agent' },
            },
            {
                id: 'llm-1',
                type: 'llm',
                position: { x: 400, y: 250 },
                data: { label: 'LLM' },
            },
            {
                id: 'memory-1',
                type: 'memory',
                position: { x: 600, y: 50 },
                data: { label: 'Memory' },
            },
            {
                id: 'tool-1',
                type: 'tool',
                position: { x: 600, y: 150 },
                data: { label: 'Search Tool' },
            },
            {
                id: 'tool-2',
                type: 'tool',
                position: { x: 600, y: 250 },
                data: { label: 'Calculator' },
            },
        ],
        edges: [
            { id: 'e1', source: 'user-1', target: 'input-1', type: 'custom' },
            { id: 'e2', source: 'input-1', target: 'agent-1', type: 'custom' },
            { id: 'e3', source: 'agent-1', target: 'llm-1', type: 'custom' },
            { id: 'e4', source: 'agent-1', target: 'memory-1', type: 'custom' },
            { id: 'e5', source: 'agent-1', target: 'tool-1', type: 'custom' },
            { id: 'e6', source: 'agent-1', target: 'tool-2', type: 'custom' },
        ],
    },
    {
        id: 'multi-agent',
        name: 'Multi-Agent System',
        description: 'Orchestrator with specialized worker agents',
        category: 'ai-agents',
        nodes: [
            {
                id: 'user-1',
                type: 'user',
                position: { x: 50, y: 200 },
                data: { label: 'User' },
            },
            {
                id: 'orchestrator-1',
                type: 'agent',
                position: { x: 250, y: 200 },
                data: { label: 'Orchestrator', color: 'hsl(217, 91%, 60%)' },
            },
            {
                id: 'agent-research',
                type: 'agent',
                position: { x: 500, y: 50 },
                data: { label: 'Research Agent' },
            },
            {
                id: 'agent-writer',
                type: 'agent',
                position: { x: 500, y: 200 },
                data: { label: 'Writer Agent' },
            },
            {
                id: 'agent-reviewer',
                type: 'agent',
                position: { x: 500, y: 350 },
                data: { label: 'Reviewer Agent' },
            },
            {
                id: 'llm-1',
                type: 'llm',
                position: { x: 750, y: 200 },
                data: { label: 'Shared LLM' },
            },
            {
                id: 'memory-1',
                type: 'memory',
                position: { x: 250, y: 400 },
                data: { label: 'Shared Memory' },
            },
        ],
        edges: [
            { id: 'e1', source: 'user-1', target: 'orchestrator-1', type: 'custom' },
            { id: 'e2', source: 'orchestrator-1', target: 'agent-research', type: 'custom' },
            { id: 'e3', source: 'orchestrator-1', target: 'agent-writer', type: 'custom' },
            { id: 'e4', source: 'orchestrator-1', target: 'agent-reviewer', type: 'custom' },
            { id: 'e5', source: 'agent-research', target: 'llm-1', type: 'custom' },
            { id: 'e6', source: 'agent-writer', target: 'llm-1', type: 'custom' },
            { id: 'e7', source: 'agent-reviewer', target: 'llm-1', type: 'custom' },
            { id: 'e8', source: 'orchestrator-1', target: 'memory-1', type: 'custom' },
        ],
    },
    {
        id: 'rag-pipeline',
        name: 'RAG Pipeline',
        description: 'Retrieval-Augmented Generation system',
        category: 'ai-agents',
        nodes: [
            {
                id: 'user-1',
                type: 'user',
                position: { x: 50, y: 150 },
                data: { label: 'User Query' },
            },
            {
                id: 'input-1',
                type: 'input',
                position: { x: 200, y: 150 },
                data: { label: 'Query Processor' },
            },
            {
                id: 'memory-1',
                type: 'memory',
                position: { x: 400, y: 50 },
                data: { label: 'Vector DB' },
            },
            {
                id: 'tool-1',
                type: 'tool',
                position: { x: 400, y: 150 },
                data: { label: 'Retriever' },
            },
            {
                id: 'agent-1',
                type: 'agent',
                position: { x: 600, y: 150 },
                data: { label: 'RAG Agent' },
            },
            {
                id: 'llm-1',
                type: 'llm',
                position: { x: 800, y: 150 },
                data: { label: 'LLM' },
            },
            {
                id: 'database-1',
                type: 'database',
                position: { x: 400, y: 280 },
                data: { label: 'Documents' },
            },
        ],
        edges: [
            { id: 'e1', source: 'user-1', target: 'input-1', type: 'custom' },
            { id: 'e2', source: 'input-1', target: 'tool-1', type: 'custom' },
            { id: 'e3', source: 'tool-1', target: 'memory-1', type: 'custom' },
            { id: 'e4', source: 'tool-1', target: 'agent-1', type: 'custom' },
            { id: 'e5', source: 'agent-1', target: 'llm-1', type: 'custom' },
            { id: 'e6', source: 'database-1', target: 'memory-1', type: 'custom' },
        ],
    },
    {
        id: 'microservices',
        name: 'Microservices Architecture',
        description: 'Basic microservices with API gateway',
        category: 'architecture',
        nodes: [
            {
                id: 'user-1',
                type: 'user',
                position: { x: 50, y: 200 },
                data: { label: 'Client' },
            },
            {
                id: 'frontend-1',
                type: 'frontend',
                position: { x: 200, y: 200 },
                data: { label: 'Web App' },
            },
            {
                id: 'backend-gateway',
                type: 'backend',
                position: { x: 400, y: 200 },
                data: { label: 'API Gateway' },
            },
            {
                id: 'backend-users',
                type: 'backend',
                position: { x: 600, y: 50 },
                data: { label: 'Users Service' },
            },
            {
                id: 'backend-orders',
                type: 'backend',
                position: { x: 600, y: 200 },
                data: { label: 'Orders Service' },
            },
            {
                id: 'backend-products',
                type: 'backend',
                position: { x: 600, y: 350 },
                data: { label: 'Products Service' },
            },
            {
                id: 'database-users',
                type: 'database',
                position: { x: 800, y: 50 },
                data: { label: 'Users DB' },
            },
            {
                id: 'database-orders',
                type: 'database',
                position: { x: 800, y: 200 },
                data: { label: 'Orders DB' },
            },
            {
                id: 'database-products',
                type: 'database',
                position: { x: 800, y: 350 },
                data: { label: 'Products DB' },
            },
        ],
        edges: [
            { id: 'e1', source: 'user-1', target: 'frontend-1', type: 'custom' },
            { id: 'e2', source: 'frontend-1', target: 'backend-gateway', type: 'custom' },
            { id: 'e3', source: 'backend-gateway', target: 'backend-users', type: 'custom' },
            { id: 'e4', source: 'backend-gateway', target: 'backend-orders', type: 'custom' },
            { id: 'e5', source: 'backend-gateway', target: 'backend-products', type: 'custom' },
            { id: 'e6', source: 'backend-users', target: 'database-users', type: 'custom' },
            { id: 'e7', source: 'backend-orders', target: 'database-orders', type: 'custom' },
            { id: 'e8', source: 'backend-products', target: 'database-products', type: 'custom' },
        ],
    },
    {
        id: 'serverless',
        name: 'Serverless Architecture',
        description: 'Cloud functions with event-driven design',
        category: 'architecture',
        nodes: [
            {
                id: 'user-1',
                type: 'user',
                position: { x: 50, y: 150 },
                data: { label: 'Client' },
            },
            {
                id: 'cloud-api',
                type: 'cloud',
                position: { x: 200, y: 150 },
                data: { label: 'API Gateway' },
            },
            {
                id: 'cloud-fn1',
                type: 'cloud',
                position: { x: 400, y: 50 },
                data: { label: 'Lambda: Auth' },
            },
            {
                id: 'cloud-fn2',
                type: 'cloud',
                position: { x: 400, y: 150 },
                data: { label: 'Lambda: Process' },
            },
            {
                id: 'cloud-fn3',
                type: 'cloud',
                position: { x: 400, y: 250 },
                data: { label: 'Lambda: Notify' },
            },
            {
                id: 'database-1',
                type: 'database',
                position: { x: 600, y: 100 },
                data: { label: 'DynamoDB' },
            },
            {
                id: 'cloud-s3',
                type: 'cloud',
                position: { x: 600, y: 250 },
                data: { label: 'S3 Storage' },
            },
        ],
        edges: [
            { id: 'e1', source: 'user-1', target: 'cloud-api', type: 'custom' },
            { id: 'e2', source: 'cloud-api', target: 'cloud-fn1', type: 'custom' },
            { id: 'e3', source: 'cloud-api', target: 'cloud-fn2', type: 'custom' },
            { id: 'e4', source: 'cloud-fn2', target: 'cloud-fn3', type: 'custom' },
            { id: 'e5', source: 'cloud-fn1', target: 'database-1', type: 'custom' },
            { id: 'e6', source: 'cloud-fn2', target: 'database-1', type: 'custom' },
            { id: 'e7', source: 'cloud-fn3', target: 'cloud-s3', type: 'custom' },
        ],
    },
    {
        id: 'basic-flowchart',
        name: 'Basic Flowchart',
        description: 'Simple process flow with start, process, decision, and end',
        category: 'flowchart',
        nodes: [
            {
                id: 'fc-start',
                type: 'flowchart-start',
                position: { x: 250, y: 50 },
                data: { label: 'Start', description: 'Process begins here' },
            },
            {
                id: 'fc-input',
                type: 'flowchart-io',
                position: { x: 250, y: 150 },
                data: { label: 'User Input', description: 'Receive user data' },
            },
            {
                id: 'fc-process1',
                type: 'flowchart-process',
                position: { x: 250, y: 250 },
                data: { label: 'Process Data', description: 'Validate and process' },
            },
            {
                id: 'fc-decision',
                type: 'flowchart-decision',
                position: { x: 250, y: 350 },
                data: { label: 'Is Valid?', description: 'Check validation result' },
            },
            {
                id: 'fc-success',
                type: 'flowchart-result',
                position: { x: 100, y: 470 },
                data: { label: 'Success', description: 'Process completed' },
            },
            {
                id: 'fc-error',
                type: 'flowchart-action',
                position: { x: 400, y: 470 },
                data: { label: 'Handle Error', description: 'Show error message' },
            },
            {
                id: 'fc-end',
                type: 'flowchart-end',
                position: { x: 250, y: 580 },
                data: { label: 'End', description: 'Process ends' },
            },
        ],
        edges: [
            { id: 'fc-e1', source: 'fc-start', target: 'fc-input', type: 'custom' },
            { id: 'fc-e2', source: 'fc-input', target: 'fc-process1', type: 'custom' },
            { id: 'fc-e3', source: 'fc-process1', target: 'fc-decision', type: 'custom' },
            { id: 'fc-e4', source: 'fc-decision', target: 'fc-success', type: 'custom', label: 'Yes', data: { labelPreset: 'success' } },
            { id: 'fc-e5', source: 'fc-decision', target: 'fc-error', type: 'custom', label: 'No', data: { labelPreset: 'error' } },
            { id: 'fc-e6', source: 'fc-success', target: 'fc-end', type: 'custom' },
            { id: 'fc-e7', source: 'fc-error', target: 'fc-end', type: 'custom' },
        ],
    },
    {
        id: 'decision-tree',
        name: 'Decision Tree',
        description: 'Multi-level decision branching structure',
        category: 'flowchart',
        nodes: [
            {
                id: 'dt-start',
                type: 'flowchart-start',
                position: { x: 350, y: 50 },
                data: { label: 'Start', description: 'Begin evaluation' },
            },
            {
                id: 'dt-condition1',
                type: 'flowchart-condition',
                position: { x: 350, y: 150 },
                data: { label: 'Condition A', description: 'First check' },
            },
            {
                id: 'dt-condition2',
                type: 'flowchart-condition',
                position: { x: 150, y: 280 },
                data: { label: 'Condition B', description: 'Second check' },
            },
            {
                id: 'dt-condition3',
                type: 'flowchart-condition',
                position: { x: 550, y: 280 },
                data: { label: 'Condition C', description: 'Third check' },
            },
            {
                id: 'dt-action1',
                type: 'flowchart-action',
                position: { x: 50, y: 410 },
                data: { label: 'Action 1', description: 'Execute path A-B' },
            },
            {
                id: 'dt-action2',
                type: 'flowchart-action',
                position: { x: 250, y: 410 },
                data: { label: 'Action 2', description: 'Execute path A-!B' },
            },
            {
                id: 'dt-action3',
                type: 'flowchart-action',
                position: { x: 450, y: 410 },
                data: { label: 'Action 3', description: 'Execute path !A-C' },
            },
            {
                id: 'dt-action4',
                type: 'flowchart-action',
                position: { x: 650, y: 410 },
                data: { label: 'Action 4', description: 'Execute path !A-!C' },
            },
            {
                id: 'dt-end',
                type: 'flowchart-end',
                position: { x: 350, y: 530 },
                data: { label: 'End', description: 'Decision complete' },
            },
        ],
        edges: [
            { id: 'dt-e1', source: 'dt-start', target: 'dt-condition1', type: 'custom' },
            { id: 'dt-e2', source: 'dt-condition1', target: 'dt-condition2', type: 'custom', label: 'Yes', data: { labelPreset: 'success' } },
            { id: 'dt-e3', source: 'dt-condition1', target: 'dt-condition3', type: 'custom', label: 'No', data: { labelPreset: 'warning' } },
            { id: 'dt-e4', source: 'dt-condition2', target: 'dt-action1', type: 'custom', label: 'Yes', data: { labelPreset: 'success' } },
            { id: 'dt-e5', source: 'dt-condition2', target: 'dt-action2', type: 'custom', label: 'No', data: { labelPreset: 'warning' } },
            { id: 'dt-e6', source: 'dt-condition3', target: 'dt-action3', type: 'custom', label: 'Yes', data: { labelPreset: 'success' } },
            { id: 'dt-e7', source: 'dt-condition3', target: 'dt-action4', type: 'custom', label: 'No', data: { labelPreset: 'warning' } },
            { id: 'dt-e8', source: 'dt-action1', target: 'dt-end', type: 'custom' },
            { id: 'dt-e9', source: 'dt-action2', target: 'dt-end', type: 'custom' },
            { id: 'dt-e10', source: 'dt-action3', target: 'dt-end', type: 'custom' },
            { id: 'dt-e11', source: 'dt-action4', target: 'dt-end', type: 'custom' },
        ],
    },
    {
        id: 'customer-service',
        name: 'Customer Service Agent',
        description: 'AI agent for lead qualification and appointment scheduling',
        category: 'ai-agents',
        nodes: [
            {
                id: 'customer-1',
                type: 'user',
                position: { x: 50, y: 200 },
                data: { label: 'Customer' },
            },
            {
                id: 'input-msg',
                type: 'input',
                position: { x: 200, y: 200 },
                data: { label: 'Message Input', description: 'WhatsApp, Email, Chat' },
            },
            {
                id: 'agent-router',
                type: 'agent',
                position: { x: 400, y: 50 },
                data: { label: 'Intent Router', description: 'Classifies customer intent' },
            },
            {
                id: 'agent-qualify',
                type: 'agent',
                position: { x: 400, y: 200 },
                data: { label: 'Qualification Agent', description: 'Qualifies leads with questions' },
            },
            {
                id: 'agent-scheduler',
                type: 'agent',
                position: { x: 400, y: 350 },
                data: { label: 'Scheduler Agent', description: 'Books appointments' },
            },
            {
                id: 'llm-1',
                type: 'llm',
                position: { x: 650, y: 200 },
                data: { label: 'Claude/GPT' },
            },
            {
                id: 'memory-history',
                type: 'memory',
                position: { x: 650, y: 50 },
                data: { label: 'Conversation History' },
            },
            {
                id: 'tool-calendar',
                type: 'tool',
                position: { x: 650, y: 350 },
                data: { label: 'Google Calendar', description: 'API for scheduling' },
            },
            {
                id: 'tool-crm',
                type: 'tool',
                position: { x: 650, y: 450 },
                data: { label: 'CRM Integration', description: 'HubSpot, Salesforce' },
            },
        ],
        edges: [
            { id: 'cs-e1', source: 'customer-1', target: 'input-msg', type: 'custom' },
            { id: 'cs-e2', source: 'input-msg', target: 'agent-router', type: 'custom' },
            { id: 'cs-e3', source: 'agent-router', target: 'agent-qualify', type: 'custom', label: 'qualify' },
            { id: 'cs-e4', source: 'agent-router', target: 'agent-scheduler', type: 'custom', label: 'schedule' },
            { id: 'cs-e5', source: 'agent-qualify', target: 'llm-1', type: 'custom' },
            { id: 'cs-e6', source: 'agent-scheduler', target: 'llm-1', type: 'custom' },
            { id: 'cs-e7', source: 'agent-qualify', target: 'memory-history', type: 'custom' },
            { id: 'cs-e8', source: 'agent-scheduler', target: 'tool-calendar', type: 'custom' },
            { id: 'cs-e9', source: 'agent-qualify', target: 'tool-crm', type: 'custom' },
        ],
    },
    {
        id: 'research-agent',
        name: 'Research Agent',
        description: 'AI agent that researches, synthesizes, and generates reports',
        category: 'ai-agents',
        nodes: [
            {
                id: 'user-query',
                type: 'user',
                position: { x: 50, y: 200 },
                data: { label: 'User' },
            },
            {
                id: 'input-query',
                type: 'input',
                position: { x: 200, y: 200 },
                data: { label: 'Research Query' },
            },
            {
                id: 'agent-orchestrator',
                type: 'agent',
                position: { x: 400, y: 200 },
                data: { label: 'Research Orchestrator', description: 'Coordinates research tasks' },
            },
            {
                id: 'tool-search',
                type: 'tool',
                position: { x: 600, y: 50 },
                data: { label: 'Web Search', description: 'Google, Bing, Tavily' },
            },
            {
                id: 'tool-reader',
                type: 'tool',
                position: { x: 600, y: 150 },
                data: { label: 'Document Reader', description: 'PDF, Web pages' },
            },
            {
                id: 'memory-notes',
                type: 'memory',
                position: { x: 600, y: 250 },
                data: { label: 'Research Notes', description: 'Collected insights' },
            },
            {
                id: 'agent-synth',
                type: 'agent',
                position: { x: 600, y: 350 },
                data: { label: 'Synthesizer', description: 'Combines findings' },
            },
            {
                id: 'llm-1',
                type: 'llm',
                position: { x: 800, y: 200 },
                data: { label: 'LLM', description: 'Analysis & synthesis' },
            },
            {
                id: 'database-output',
                type: 'database',
                position: { x: 800, y: 350 },
                data: { label: 'Report Output' },
            },
        ],
        edges: [
            { id: 'ra-e1', source: 'user-query', target: 'input-query', type: 'custom' },
            { id: 'ra-e2', source: 'input-query', target: 'agent-orchestrator', type: 'custom' },
            { id: 'ra-e3', source: 'agent-orchestrator', target: 'tool-search', type: 'custom' },
            { id: 'ra-e4', source: 'agent-orchestrator', target: 'tool-reader', type: 'custom' },
            { id: 'ra-e5', source: 'tool-search', target: 'memory-notes', type: 'custom' },
            { id: 'ra-e6', source: 'tool-reader', target: 'memory-notes', type: 'custom' },
            { id: 'ra-e7', source: 'memory-notes', target: 'agent-synth', type: 'custom' },
            { id: 'ra-e8', source: 'agent-synth', target: 'llm-1', type: 'custom' },
            { id: 'ra-e9', source: 'agent-synth', target: 'database-output', type: 'custom' },
        ],
    },
    {
        id: 'code-review',
        name: 'Code Review Agent',
        description: 'AI agent that analyzes PRs and suggests improvements',
        category: 'ai-agents',
        nodes: [
            {
                id: 'dev-user',
                type: 'user',
                position: { x: 50, y: 200 },
                data: { label: 'Developer' },
            },
            {
                id: 'input-pr',
                type: 'input',
                position: { x: 200, y: 200 },
                data: { label: 'PR / Diff', description: 'Code changes to review' },
            },
            {
                id: 'agent-analyzer',
                type: 'agent',
                position: { x: 400, y: 100 },
                data: { label: 'Code Analyzer', description: 'Parses and understands code' },
            },
            {
                id: 'agent-reviewer',
                type: 'agent',
                position: { x: 400, y: 250 },
                data: { label: 'Review Agent', description: 'Generates review comments' },
            },
            {
                id: 'tool-github',
                type: 'tool',
                position: { x: 600, y: 50 },
                data: { label: 'GitHub API', description: 'Fetch PR details' },
            },
            {
                id: 'tool-linter',
                type: 'tool',
                position: { x: 600, y: 150 },
                data: { label: 'Linter', description: 'ESLint, Prettier' },
            },
            {
                id: 'memory-standards',
                type: 'memory',
                position: { x: 600, y: 250 },
                data: { label: 'Code Standards', description: 'Team conventions' },
            },
            {
                id: 'llm-1',
                type: 'llm',
                position: { x: 600, y: 350 },
                data: { label: 'LLM', description: 'Code understanding' },
            },
            {
                id: 'database-comments',
                type: 'database',
                position: { x: 800, y: 200 },
                data: { label: 'Review Comments' },
            },
        ],
        edges: [
            { id: 'cr-e1', source: 'dev-user', target: 'input-pr', type: 'custom' },
            { id: 'cr-e2', source: 'input-pr', target: 'agent-analyzer', type: 'custom' },
            { id: 'cr-e3', source: 'agent-analyzer', target: 'tool-github', type: 'custom' },
            { id: 'cr-e4', source: 'agent-analyzer', target: 'tool-linter', type: 'custom' },
            { id: 'cr-e5', source: 'agent-analyzer', target: 'agent-reviewer', type: 'custom' },
            { id: 'cr-e6', source: 'agent-reviewer', target: 'memory-standards', type: 'custom' },
            { id: 'cr-e7', source: 'agent-reviewer', target: 'llm-1', type: 'custom' },
            { id: 'cr-e8', source: 'agent-reviewer', target: 'database-comments', type: 'custom' },
        ],
    },
    {
        id: 'rag-reranking',
        name: 'RAG with Reranking',
        description: 'Advanced RAG pipeline with reranking for better precision',
        category: 'ai-agents',
        nodes: [
            {
                id: 'user-1',
                type: 'user',
                position: { x: 50, y: 200 },
                data: { label: 'User Query' },
            },
            {
                id: 'input-query',
                type: 'input',
                position: { x: 200, y: 200 },
                data: { label: 'Query Processor' },
            },
            {
                id: 'tool-embedder',
                type: 'tool',
                position: { x: 350, y: 100 },
                data: { label: 'Embedding Model', description: 'text-embedding-3' },
            },
            {
                id: 'memory-vectordb',
                type: 'memory',
                position: { x: 350, y: 300 },
                data: { label: 'Vector Database', description: 'Pinecone, Weaviate' },
            },
            {
                id: 'agent-retriever',
                type: 'agent',
                position: { x: 500, y: 200 },
                data: { label: 'Retriever', description: 'Fetches top-k docs' },
            },
            {
                id: 'agent-reranker',
                type: 'agent',
                position: { x: 650, y: 200 },
                data: { label: 'Reranker', description: 'Reorders by relevance' },
            },
            {
                id: 'llm-1',
                type: 'llm',
                position: { x: 800, y: 200 },
                data: { label: 'LLM', description: 'Answer generation' },
            },
            {
                id: 'database-docs',
                type: 'database',
                position: { x: 500, y: 350 },
                data: { label: 'Document Store' },
            },
        ],
        edges: [
            { id: 'rr-e1', source: 'user-1', target: 'input-query', type: 'custom' },
            { id: 'rr-e2', source: 'input-query', target: 'tool-embedder', type: 'custom' },
            { id: 'rr-e3', source: 'tool-embedder', target: 'memory-vectordb', type: 'custom' },
            { id: 'rr-e4', source: 'memory-vectordb', target: 'agent-retriever', type: 'custom' },
            { id: 'rr-e5', source: 'agent-retriever', target: 'agent-reranker', type: 'custom' },
            { id: 'rr-e6', source: 'agent-reranker', target: 'llm-1', type: 'custom' },
            { id: 'rr-e7', source: 'database-docs', target: 'memory-vectordb', type: 'custom' },
        ],
    },
    {
        id: 'data-pipeline-etl',
        name: 'Data Pipeline (ETL)',
        description: 'Extract, Transform, Load pipeline with validation',
        category: 'flowchart',
        nodes: [
            {
                id: 'etl-start',
                type: 'flowchart-start',
                position: { x: 300, y: 50 },
                data: { label: 'Start', description: 'Pipeline triggered' },
            },
            {
                id: 'etl-extract',
                type: 'flowchart-process',
                position: { x: 300, y: 150 },
                data: { label: 'Extract', description: 'Fetch from source' },
            },
            {
                id: 'etl-validate-schema',
                type: 'flowchart-condition',
                position: { x: 300, y: 260 },
                data: { label: 'Valid Schema?', description: 'Check data structure' },
            },
            {
                id: 'etl-transform',
                type: 'flowchart-process',
                position: { x: 150, y: 380 },
                data: { label: 'Transform', description: 'Clean & normalize' },
            },
            {
                id: 'etl-error-log',
                type: 'flowchart-action',
                position: { x: 450, y: 380 },
                data: { label: 'Log Error', description: 'Record validation failure' },
            },
            {
                id: 'etl-quality-check',
                type: 'flowchart-condition',
                position: { x: 150, y: 500 },
                data: { label: 'Quality OK?', description: 'Data quality check' },
            },
            {
                id: 'etl-load',
                type: 'flowchart-process',
                position: { x: 50, y: 620 },
                data: { label: 'Load', description: 'Insert into warehouse' },
            },
            {
                id: 'etl-quarantine',
                type: 'flowchart-action',
                position: { x: 250, y: 620 },
                data: { label: 'Quarantine', description: 'Flag for review' },
            },
            {
                id: 'etl-end',
                type: 'flowchart-end',
                position: { x: 150, y: 740 },
                data: { label: 'End', description: 'Pipeline complete' },
            },
        ],
        edges: [
            { id: 'etl-e1', source: 'etl-start', target: 'etl-extract', type: 'custom' },
            { id: 'etl-e2', source: 'etl-extract', target: 'etl-validate-schema', type: 'custom' },
            { id: 'etl-e3', source: 'etl-validate-schema', target: 'etl-transform', type: 'custom', label: 'Yes', data: { labelPreset: 'success' } },
            { id: 'etl-e4', source: 'etl-validate-schema', target: 'etl-error-log', type: 'custom', label: 'No', data: { labelPreset: 'error' } },
            { id: 'etl-e5', source: 'etl-transform', target: 'etl-quality-check', type: 'custom' },
            { id: 'etl-e6', source: 'etl-quality-check', target: 'etl-load', type: 'custom', label: 'Yes', data: { labelPreset: 'success' } },
            { id: 'etl-e7', source: 'etl-quality-check', target: 'etl-quarantine', type: 'custom', label: 'No', data: { labelPreset: 'warning' } },
            { id: 'etl-e8', source: 'etl-load', target: 'etl-end', type: 'custom' },
            { id: 'etl-e9', source: 'etl-quarantine', target: 'etl-end', type: 'custom' },
            { id: 'etl-e10', source: 'etl-error-log', target: 'etl-end', type: 'custom' },
        ],
    },
    {
        id: 'blank',
        name: 'Blank Canvas',
        description: 'Start from scratch',
        category: 'general',
        nodes: [],
        edges: [],
    },
];

export function getTemplatesByCategory(category?: string) {
    if (!category || category === 'all') return DIAGRAM_TEMPLATES;
    return DIAGRAM_TEMPLATES.filter((t) => t.category === category);
}
